---
- name: PHP | CHECK REMI REPO
  yum: name=remi-release state=present
  register: find_remi
  ignore_errors: true

- name: PHP | INSTALL REMI
  yum: name=http://rpms.famillecollet.com/enterprise/remi-release-7.rpm state=present
  when: find_remi|failed

- name: PHP | INSTALL DEFAULT MODULES
  yum: name={{ item }} state=present enablerepo=remi,remi-php70
  with_items:
    - php-cli
    - php-process
    - php-imap
    - php-xml
    - php-common
    - php-fpm
    - php-pdo
    - php-mysqlnd
    - php-mcrypt
    - php-mbstring
    - php-bcmath
    - php-mbstring
    - php-intl
    - php-gd
    - php-pecl-jsonc
    - php-opcache
  notify: restart php-fpm

- name: PHP | INSTALL ADDITIONAL MODULES
  yum: name={{ item }} state=present enablerepo=remi,remi-php70
  with_items: "{{ modules }}"

- name: PHP | RUN FPM ON STARTUP
  service: name=php-fpm enabled=yes state=started

- name: PHP | UPDATE FPM CONFIG
  lineinfile: dest={{ php_pool_file }} regexp='^;?catch_workers_output\s?=.*$' line=catch_workers_output=yes
  notify: restart php-fpm

- name: PHP | UPDATE FPM SOCKET
  lineinfile: dest={{ php_pool_file }} regexp='^;?listen\s?=.*$' line=listen=127.0.0.1:9000
  notify: restart php-fpm

- name: PHP | SET FPM GROUP
  lineinfile: dest={{ php_pool_file }} regexp="^group\s?=.*$" line="group = {{ group }}"
  notify: restart php-fpm

- name: PHP | SET FPM USER
  lineinfile: dest={{ php_pool_file }} regexp="^user\s?=.*$" line="user = {{ user }}"
  notify: restart php-fpm

- name: PHP | SET OWNERSHIP
  file: path=/var/lib/php/session owner={{ user }} group={{ group }} state=directory
  notify: restart php-fpm

- name: PHP | SET PHP INI PARAMS
  lineinfile: dest={{ php_ini }} regexp='^;?{{ item.key }} *=.*$' line="{{ item.key }}={{ item.value }}"
  with_dict: "{{ params }}"
  notify: reload php-fpm
